[default]
binary = false
check-filename = true

[default.extend-identifiers]
referes = "referes"
StatuS = "StatuS"

[default.extend-words]
# ECN Capable Transport
ect = "ect"
# Packet Number
pn = "pn"
# Retransmission Timeout
RTO = "RTO"

[files]
extend-exclude = [
    "*.snap",
    "*.bin",
    "*.der",
    "*.pem",
    "LICENSE",
    "**/target/**/*",
    "**/deps/**/*",
    "**/corpus/**/*",
]
