name: Rust

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - name: Code format check
      run: cargo fmt --check

    - name: Build TQUIC library
      run: cargo build -F ffi --verbose

    - name: Build TQUIC examples
      run: cargo build --all --verbose

    - name: Code lint check
      run: cargo clippy

    - name: Run unit tests
      run: cargo test --verbose

    - name: Report coverage
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      run: |
        cargo install cargo-tarpaulin
        cargo tarpaulin --exclude-files "src/third_party/*" --out Xml
        bash <(curl -s https://codecov.io/bash) -X gcov -t $CODECOV_TOKEN
