name: Rust

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  static_analysis:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - name: Update rust
      run: rustup update

    - name: Code format check
      run: cargo fmt --check

    - name: Code lint check
      run: cargo clippy --all -- -D warnings

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - name: Update rust
      run: rustup update
      
    - name: Build TQUIC library
      run: cargo build -F ffi --verbose

    - name: Build TQUIC tools
      run: cargo build --all --verbose

  unit_testing:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - name: Update rust
      run: rustup update

    - name: Unit testing
      run: cargo test --verbose

  fuzz_testing:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - name: Fuzz testing
      run: |
        rustup install nightly
        rustup default nightly
        cargo install cargo-fuzz
        cargo fuzz run client_conn -- -max_total_time=30
        cargo fuzz run server_conn -- -max_total_time=30
 
